### ISSUE TITLE
MQTT Discovery in Homeassistant

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1133]
- [x] Implement
 - [x] Update wiki page https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant

**Comment by caco3** [comment]
See https://github.com/jomjol/AI-on-the-edge-device/issues/1108

**Comment by dcboy87** [comment]
okay, i also played a bit today, maybe the problem is formatting of the JSON payload. I tried with this example:

````
{
  "~": "watermeter",
  "name": "Meter-Water - Counter",
  "unit_of_meas": "m³",
  "icon": "mdi:water",
  "state_topic": "~/main/json",
  "value_template": "{{ value_json.value}}",
  "json_attributes_topic": "~/main/json",
  "unique_id": "smartmeter.watertotal.total",
  "availability_topic": "~/connection",
  "payload_available": "connected",
  "payload_not_available": "connection lost",
  "device": {
    "identifiers": ["12345678"],
    "name": "Total water meter",
    "model": "M100",
    "manufacturer": "aquamess"
    }
  }
````

then in HA this device gets discovered:

![grafik](https://user-images.githubusercontent.com/45015463/194227591-331de1b2-4dc2-435a-8d64-d3277e5e44b3.png)
![grafik](https://user-images.githubusercontent.com/45015463/194227834-1a5663eb-fc1c-4861-b159-98c678894261.png)

**Comment by caco3** [comment]
thanks for testing it!
I tried to use your example in the HA MQTT sending pat, but that did not work at all (no message gets sent at all, monitored with http://mqtt-explorer.com).
Then i sent the very same message/topic using http://mqtt-explorer.com. Then suddenly HA saw it and showed the new device.

So it seems to work in general.
I will have a look on in some weeks (am on holiday right now).

**Comment by caco3** [comment]
I now got it working with a Python MQTT client.
I will try to implement it on ESP side after my holidays.

**Comment by dcboy87** [comment]
thank you very much! Great work 💪

**Comment by Liese2007** [comment]
Hi,
have actually problems getting my sensor to transmit data to Home Assistant via mqtt broker.
Is my understanding right, that I have actually to wait for next release?

Here is my log, just in case my fault is a different one:
```
DigitalUnschaerfe = 0.200000
2022-10-19T20:38:45: ClassFlowCNNGeneral::getReadout#ZeigerEvalHybridNeu()= 1
2022-10-19T20:38:45: ClassFlowCNNGeneral::getReadout#result= 11933
2022-10-19T20:38:45: PostProcessing - Raw: 119.33 Value: 119.33 Error: no error
2022-10-19T20:38:45: 	FlowControll.doFlow - ClassFlowMQTT
2022-10-19T20:38:45: MQTT - Failed to publish 'watermeter/connection'!
2022-10-19T20:38:45: MQTT - Re-running init...!
2022-10-19T20:38:45: MQTT - Init
2022-10-19T20:38:45: MQTT - Could not Init client!
2022-10-19T20:38:45: task_autodoFlow - round done
2022-10-19T20:38:45: CPU Temperature: 53.3
2022-10-19T20:41:57: download_get_handler
```
Greets Joerg

**Comment by caco3** [comment]
You could try to restart and check again.
It works in general, but not very stable, meaning sometimes it needs multiple retries or runs to success

**Comment by Henry-Sir** [comment]
Generally it works and also stable.
But please note the info in post https://github.com/jomjol/AI-on-the-edge-device/issues/299#issuecomment-993448517:


_Don't forget to update your mqtt topic in "~".
For the device ID take a uniqe number, not "12345678"._

mptt topic is set in the config of the ESP:
![image](https://user-images.githubusercontent.com/75314095/196939185-29eb5f12-522a-454f-9935-42c1809d7301.png)




### my current status
![image](https://user-images.githubusercontent.com/75314095/196938859-46168855-e7c9-43b9-9aeb-919e98b6e668.png)


![image](https://user-images.githubusercontent.com/75314095/196938372-6932413a-deea-4b40-ae89-20003e083318.png)

![image](https://user-images.githubusercontent.com/75314095/196938925-0ff9e3ce-e991-4fc7-a478-c9045825c342.png)

**Comment by caco3** [comment]
I have a partially working version running on the ESP32 (see branch [add-homeassistant-discovery](https://github.com/jomjol/AI-on-the-edge-device/tree/add-homeassistant-discovery)). give me another 1..2 weeks to clean everything up first.

**Comment by caco3** [comment]
Will be implemented in https://github.com/jomjol/AI-on-the-edge-device/pull/1234

@dcboy87 and @Henry-Sir could you test if it works for you before we merge it? Use the update file from https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3341110238

**Comment by Henry-Sir** [comment]
Looks good


The icon of the RSSI could still be adjusted. Either change the icon to "mdi:wifi". Or remove icon and add device class: _"device_class": "signal_strength"_ (https://www.home-assistant.io/integrations/sensor/#device-class  (https://www.home-assistant.io/integrations/sensor/#device-class)

An additional alarm sensor could be added to the "Error" sensor. I have set up a "binary sensor" for this, see below.

Icon proposal for the rate senors: "mdi:swap-vertical"


![image](https://user-images.githubusercontent.com/75314095/198574651-60dd2d68-ffaf-4148-98f3-d932c8c8405a.png)
![image](https://user-images.githubusercontent.com/75314095/198569228-0419fac3-f50e-4895-b8b0-012ff1bc888d.png)

### Error binary sensor ###
MQTT
```
{
  "~": "watermeter",
  "name": "Meter-Water - Alarm",
  "icon": "mdi:alert",
  "state_topic": "~/main/error",
  "value_template": "{{ 'OFF' if 'no error' in value else 'ON'}}",
  "json_attributes_topic": "~/main/json",
  "unique_id": "smartmeter.watertotal.error",
  "availability_topic": "~/connection",
  "payload_available": "connected",
  "payload_not_available": "connection lost",
  "device": {
    "identifiers": ["51131348"],
    "name": "Wasserzähler Gesamt",
    "model": "M100",
    "manufacturer": "aquamess"
  }
}
```
![image](https://user-images.githubusercontent.com/75314095/198571921-eeda1675-3fb9-4832-bc6c-033d59218de9.png)
![image](https://user-images.githubusercontent.com/75314095/198574326-7e131e62-f4b3-40ab-86fa-0e402b5dc859.png)

**Comment by caco3** [comment]
@Henry-Sir thanks, I will have a look on it. Also I think it would be great when the value and rate would have a unit. But for that I need to add extra parameters in the config.

**Comment by andre68723** [comment]
just a quick question, now that HA integrated water also in the energy dashboard, will you report m^3 or liters?

See also https://github.com/home-assistant/frontend/pull/14223

**Comment by caco3** [comment]
ah, nice, I also missed that :+1: 

As of now it will not report units for the measurement values. The reason is that it also could be kWh if you have an electric meter.
If we want to add units, we have to make it configurable. I might add that later.

**Comment by caco3** [comment]
The sensors not each as a MQTT topic but as a subtopic

Done, how ever sadly only 1 level is supported

> icon to "mdi:wifi"
> Icon proposal for the rate senors: "mdi:swap-vertical"

Done

> An additional alarm sensor could be added to the "Error" sensor. I have set up a "binary sensor" for this, see below.

Done (called `Problem`)

**Comment by andre68723** [comment]
> ah, nice, I also missed that 👍
> 
> As of now it will not report units for the measurement values. The reason is that it also could be kWh if you have an electric meter. If we want to add units, we have to make it configurable. I might add that later.

Cool! 
one more thing which I noticed.
IMO a lot of the exposed sensors could be moved to "Diagnostics" or even hidden. 

see https://developers.home-assistant.io/blog/2021/10/26/config-entity/ 

Tasmota did once that change and it's a lot clean one, 2 pics (2nd is the hidden diagnostics)
![Bildschirm­foto 2022-10-30 um 10 49 34](https://user-images.githubusercontent.com/16468234/198872600-b05b57e8-1b1c-4040-a2db-19db4e175549.png)

![Bildschirm­foto 2022-10-30 um 10 49 39](https://user-images.githubusercontent.com/16468234/198872604-962ff9f7-c9bf-41a9-995a-f37f446f9b0c.png)

**Comment by Henry-Sir** [comment]
> just a quick question, now that HA integrated water also in the energy dashboard, will you report m^3 or liters?
> 
> See also [home-assistant/frontend#14223](https://github.com/home-assistant/frontend/pull/14223)

For this we need "state_class" in the MQTT publish message for the "main value" sensor. I thing total_increasing -> "state_class":"total_increasing" is the right one here.
https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes



> ah, nice, I also missed that 👍
> 
> As of now it will not report units for the measurement values. The reason is that it also could be kWh if you have an electric meter. If we want to add units, we have to make it configurable. I might add that later.

I think it would be good to specify the device class in the MQTT publish message.
Energy meter:  "device class":"energy"
Gas meter: "device class":"gas"
Water meter: "device class":"water"

https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes




> Cool! one more thing which I noticed. IMO a lot of the exposed sensors could be moved to "Diagnostics" or even hidden.
> 
> my Proposal:
> 
>* only rate and value as sensor
>* rest as diagnostics
> * IP -> remove (already under the Visit-Link)

I agree with that MQTT publish message "entity_category":"diagnostic"

**Comment by caco3** [comment]
> IMO a lot of the exposed sensors could be moved to "Diagnostics" or even hidden.

Cool, thanks, I din't know that yet, will try to add it.

> my Proposal:
    - only rate and value as sensor
    - rest as diagnostics
    - IP -> remove (already under the Visit-Link)

- Error and problem should also be sensors IMO

I will keep the IP as diagnostics. It is important for those not using HA or Discovery!

> I think it would be good to specify the device class in the MQTT publish message.
Energy meter: "device class":"energy"
Gas meter: "device class":"gas"
Water meter: "device class":"water"

I need to add config parameters for this. Additionally I have to add fields for the units as it is not obvious eg. if water is in m3, l or even something else.

> For this we need "state_class" in the MQTT publish message for the "main value" sensor. I thing total_increasing -> "state_class":"total_increasing" is the right one here.

I added that already in the latest version

BTW, `Firmware version` should not be shown as a sensor, its already part of the device!

**Comment by caco3** [comment]
@Henry-Sir @andre68723 @dcboy87  I think I implemented all your changes. Please try it with the latest build in the [enhance-homeassistant-discovery](https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Aenhance-homeassistant-discovery) branch.

I did not test it very intensively or played with all config options. So if you could do it, that would be of great help!

Can somebody test that the water dashboard works in the beta release of HA?

![grafik](https://user-images.githubusercontent.com/1783586/198902544-be46c228-f850-4d91-954a-31c1f31e1d0c.png)

**Comment by andre68723** [comment]
Sure, will test. Migration would be:
* removing from configuration.yaml any mqtt sensors + binary sensors
* enable discovery + meter type
* wait for HA to discover the new device

The last part did not happen yet on my install

**Comment by caco3** [comment]
You don't need to remove the manually created sensors for testing, HA will just disable them and throw a warning!
But you have to enable Discovery in the settings for your device now and I added a config parameter for it and the default is `DISABLED`!

If it still does not work, please check the logfile of the device.

**Comment by andre68723** [comment]
How often do you send the discovery topic?

There was one at 2022-10-31T08:44:42

```
2022-10-31T08:21:16 <INF> =============================================================================================
2022-10-31T08:21:16 <INF> =================================== Main Started ============================================
2022-10-31T08:21:16 <INF> =============================================================================================
2022-10-31T08:21:16 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T08:21:16 <INF> Reset reason: Via esp_restart
2022-10-31T08:21:21 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T08:21:21 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: AIOTED-FC:F5:C4:30:CD:D8, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T08:21:21 <INF> MQTT - Init
2022-10-31T08:21:21 <INF> MQTT - Init successful
2022-10-31T08:23:45 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T08:23:45 <INF> =============================================================================================
2022-10-31T08:23:45 <INF> =================================== Main Started ============================================
2022-10-31T08:23:45 <INF> =============================================================================================
2022-10-31T08:23:45 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T08:23:45 <INF> Reset reason: Via esp_restart
2022-10-31T08:23:50 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T08:23:50 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: AIOTED-FC:F5:C4:30:CD:D8, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T08:23:50 <INF> MQTT - Init
2022-10-31T08:23:50 <INF> MQTT - Init successful
2022-10-31T08:23:50 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T08:23:50 <INF> task_autodoFlow - next round - Round #1
2022-10-31T08:24:25 <WRN> MQTT - Not connected, trying to re-connect...
2022-10-31T08:24:25 <INF> MQTT - Init
2022-10-31T08:28:11 <INF> MQTT - Init successful
2022-10-31T08:44:42 <INF> MQTT - Connected
2022-10-31T08:44:42 <INF> MQTT - Sending Homeassistant Discovery Topics (Meter Type: water, Value Unit: L , Rate Unit: L/h)...
2022-10-31T08:44:43 <INF> logfiles deleted: 0 files not deleted (incl. leer.txt): 3
2022-10-31T08:44:44 <INF> task_autodoFlow - round done
2022-10-31T08:44:44 <INF> CPU Temperature: 53.3
2022-10-31T08:44:44 <INF> task_autodoFlow - next round - Round #2
2022-10-31T08:45:18 <INF> PostProcessing - Raw: 569.2683 Value: 569.2683 Error: no error
2022-10-31T08:45:19 <INF> logfiles deleted: 0 files not deleted (incl. leer.txt): 3
2022-10-31T08:45:19 <INF> task_autodoFlow - round done
2022-10-31T08:45:20 <INF> CPU Temperature: 53.3
2022-10-31T08:49:35 <INF> task_autodoFlow - next round - Round #3
2022-10-31T08:49:35 <INF> info_get_handler
2022-10-31T08:49:36 <INF> info_get_handler
2022-10-31T08:50:10 <INF> PostProcessing - Raw: 569.2683 Value: 569.2683 Error: no error
2022-10-31T08:50:11 <INF> logfiles deleted: 0 files not deleted (incl. leer.txt): 3
2022-10-31T08:50:11 <INF> task_autodoFlow - round done
2022-10-31T08:50:11 <INF> CPU Temperature: 73.3
2022-10-31T08:51:27 <INF> Reboot triggered by Software (5s).
2022-10-31T08:51:27 <WRN> Reboot in 5sec
2022-10-31T08:51:51 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T08:51:51 <INF> =============================================================================================
2022-10-31T08:51:51 <INF> =================================== Main Started ============================================
2022-10-31T08:51:51 <INF> =============================================================================================
2022-10-31T08:51:51 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T08:51:51 <INF> Reset reason: Via esp_restart
2022-10-31T08:51:55 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T08:51:55 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: wasser, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T08:51:55 <INF> MQTT - Init
2022-10-31T08:51:55 <INF> MQTT - Init successful
2022-10-31T09:12:57 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T09:12:57 <INF> =============================================================================================
2022-10-31T09:12:58 <INF> =================================== Main Started ============================================
2022-10-31T09:12:58 <INF> =============================================================================================
2022-10-31T09:12:58 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T09:12:58 <INF> Reset reason: Via esp_restart
2022-10-31T09:13:02 <INF> info_get_handler
2022-10-31T09:13:03 <INF> info_get_handler
2022-10-31T09:13:03 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T09:13:03 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: wasser, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T09:13:03 <INF> MQTT - Init
2022-10-31T09:13:03 <INF> MQTT - Init successful
2022-10-31T09:18:24 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T09:18:24 <INF> =============================================================================================
2022-10-31T09:18:24 <INF> =================================== Main Started ============================================
2022-10-31T09:18:24 <INF> =============================================================================================
2022-10-31T09:18:24 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T09:18:24 <INF> Reset reason: Via esp_restart
2022-10-31T09:18:29 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T09:18:29 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: wasser, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T09:18:29 <INF> MQTT - Init
2022-10-31T09:18:29 <INF> MQTT - Init successful
```


btw - home assistant didn't like the timezone


```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:679
Integration: Sensor ([documentation](https://rc.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 08:56:44 (1 occurrences)
Last logged: 08:56:44

Error adding entities for domain sensor with platform mqtt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 679, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.watermeter_main_timestamp provides state '2022-10-31 08:52:03', which is missing timezone information
```

**Comment by caco3** [comment]
> How often do you send the discovery topic?

Once on startup:
```
2022-10-31T08:23:45 <INF> =============================================================================================
2022-10-31T08:23:45 <INF> =================================== Main Started ============================================
2022-10-31T08:23:45 <INF> =============================================================================================
2022-10-31T08:23:45 <INF> Branch: 'HEAD', Tag: '', Revision: 9303778, Date/Time: 2022-10-30 23:02
2022-10-31T08:23:45 <INF> Reset reason: Via esp_restart
2022-10-31T08:23:50 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-10-31T08:23:50 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: AIOTED-FC:F5:C4:30:CD:D8, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-10-31T08:23:50 <INF> MQTT - Init
2022-10-31T08:23:50 <INF> MQTT - Init successful
2022-10-31T08:23:50 <INF> Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2022-10-31T08:23:50 <INF> task_autodoFlow - next round - Round #1
2022-10-31T08:24:25 <WRN> MQTT - Not connected, trying to re-connect...
2022-10-31T08:24:25 <INF> MQTT - Init
2022-10-31T08:28:11 <INF> MQTT - Init successful
2022-10-31T08:44:42 <INF> MQTT - Connected
2022-10-31T08:44:42 <INF> MQTT - Sending Homeassistant Discovery Topics (Meter Type: water, Value Unit: L , Rate Unit: L/h)...
```

Since the retain flag is set, HA should also pick it up if it got started later.
Maybe check with MQTT Explorer.

> btw - home assistant didn't like the timezone

I didn't change anything on the timestamp, but I set it to `date` in the discovery. But it seems that I have to adjust the timestamp format now.

**Comment by haverland** [comment]
Short status of to the current open PR:

Openhab discovery works:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/412645/199102026-b1bcdc49-5f4c-4647-b603-fa17d57b5dc9.png">

Only the units not be set, but it is a bug of openhab discovery

**Comment by caco3** [comment]
@andre68723 The firmware currently does not know the timezone offset as number. We would need to modify the config to provide the offset instead of the used timezone string (eg. `CET-1CEST,M3.5.0,M10.5.0/3`). Since that is not trivial, I will remove the device_class of the `timestamp` topic for now!

**Comment by haverland** [comment]
No. The plugin is named homeassistent discovery in Openhab.

**Comment by andre68723** [comment]
> * Added a `rate2` topic which is in hours for energy and m³/h. **If somebody has a better name, please let me know.**

`rate` and `rate_cubic`?

I still have a question with "how often do you send the discovery". 
I updated HA and the firmware, reboot log shows no announcement

```
2022-11-01T08:37:46 <INF> =============================================================================================
2022-11-01T08:37:46 <INF> =================================== Main Started ============================================
2022-11-01T08:37:46 <INF> =============================================================================================
2022-11-01T08:37:46 <INF> Branch: 'HEAD', Tag: '', Revision: 4d6f1f6, Date/Time: 2022-11-01 06:56
2022-11-01T08:37:46 <INF> Reset reason: Via esp_restart
2022-11-01T08:37:50 <INF> Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-11-01T08:37:51 <INF> MQTT Configuration: uri: mqtt://192.168.0.19:1883, clientname: wasser, user: mqttuser, password: XXXXXXXX, maintopic: watermeter, last-will-topic: watermeter/connection, keepAlive: 1500
2022-11-01T08:37:51 <INF> MQTT - Init
2022-11-01T08:37:51 <INF> MQTT - Init successful
```

**Comment by caco3** [comment]
> `rate` and `rate_cubic`?

This will not work as it also could be eg. `kW` :)

> I still have a question with "how often do you send the discovery".

It only happens on startup.
See my log below:
```

2022-11-01T07:50:57	<INF>	=================================== Main Started ============================================
2022-11-01T07:50:57	<INF>	=============================================================================================
2022-11-01T07:50:57	<INF>	Branch: 'HEAD', Tag: '', Revision: f35d540+, Date/Time: 2022-11-01 00:10
2022-11-01T07:50:57	<INF>	Reset reason: Exception/panic
2022-11-01T07:51:02	<INF>	Digitizer interval is 10.000000 minutes => setting MQTT LWT timeout to 25 minutes.
2022-11-01T07:51:02	<INF>	MQTT Configuration: uri: mqtt://192.168.1.99:1883, clientname: gaszaehler, user: , password: XXXXXXXX, maintopic: gaszaehler, last-will-topic: gaszaehler/connection, keepAlive: 1500
2022-11-01T07:51:02	<INF>	MQTT - Init
2022-11-01T07:51:02	<INF>	MQTT - Init successful
2022-11-01T07:51:03	<INF>	MQTT - Connected
2022-11-01T07:51:03	<INF>	MQTT - Sending Homeassistant Discovery Topics (Meter Type: , Value Unit:  , Rate Unit: Unit/Minute)...
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/CPU_temperature/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-CPU_temperature", "object_id": "ga.. (msg_id=9619)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/interval/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-interval", "object_id": "gaszaehle.. (msg_id=53723)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/IP/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-IP", "object_id": "gaszaehler_IP",.. (msg_id=1966)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_value/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_value", "object_id": "gaszaeh.. (msg_id=57446)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_raw/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_raw", "object_id": "gaszaehle.. (msg_id=33161)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_error/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_error", "object_id": "gaszaeh.. (msg_id=32095)
2022-11-01T07:51:03	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_rate/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_rate", "object_id": "gaszaehl.. (msg_id=40094)
2022-11-01T07:51:03	<INF>	task_autodoFlow - next round - Round #1
2022-11-01T07:51:03	<DBG>	FlowControll.doFlow - ClassFlowMakeImage		Heap:	3031242	Min Free:	2095654	
[..]
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_rate2/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_rate2", "object_id": "gaszaeh.. (msg_id=22725)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_rate_per_interval/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_rate_per_interval", "object_i.. (msg_id=46938)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_timestamp/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_timestamp", "object_id": "gas.. (msg_id=25101)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_json/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_json", "object_id": "gaszaehl.. (msg_id=59532)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: homeassistant/sensor/gaszaehler/main_problem/config, content: { "~": "gaszaehler", "unique_id": "gaszaehler-main_problem", "object_id": "gasza.. (msg_id=22547)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: gaszaehler/MAC, content: EC:94:CB:6E:18:68 (msg_id=886)
2022-11-01T07:51:04	<DBG>	MQTT - Published topic: gaszaehler/IP, content: 192.168.1.152 (msg_id=29104)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/hostname, content: Gaszaehler (msg_id=30174)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/interval, content: 2.000000 (msg_id=24347)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/uptime, content: 8 (msg_id=38966)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/free_memory, content: 2110171 (msg_id=7613)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/wifi_RSSI, content: -74 (msg_id=38473)
2022-11-01T07:51:05	<DBG>	MQTT - Published topic: gaszaehler/CPU_temperature, content: 52 (msg_id=45929)
```

I updated HA and the firmware, reboot log shows no announcement.
PS: is there a diff between reboot after fw upgrade/power cycling and the reboot by software?

reboot through fw update or SW are the same (warm start). a power cycle is a cold start as power gets removed quickly.

**Comment by andre68723** [comment]
thanks, did you read my (last edit) before you answered? I toggled it off and on and rebooted, still nothing

**Comment by caco3** [comment]
@andre68723 Please set the loglevel of the logfile to DEBUG and the settings in your screenshot. Then and restart and wait until it completes the first run.
Then please attach the logfile here.

As you can see in my comment, the HA Discovery runs within 10s after `========= Main Started =======`.

**Comment by andre68723** [comment]
after setting to debug it worked 🤔

Perfect!


PS: do you plan to keep the json on the Entity sensor page? Eventually better fits into diagnostics

![Bildschirm­foto 2022-11-01 um 22 27 47](https://user-images.githubusercontent.com/16468234/199345190-d37d8375-b0a4-45cf-973e-149d95c4d550.png)

**Comment by caco3** [comment]
> PS: do you plan to keep the json on the Entity sensor page? Eventually better fits into diagnostics

Yes, I was thinking about this as well.
But some users prefer to only use one topic (this one) and parse it in HA to get all info. Then for those its not a diagnostic value...

**Comment by andre68723** [comment]
HA b6 - now converted automatically to liters. Was thinking if they stay with m^3 its hard to read 0.x, but now in Liters and some significant consumption today  😆
![Bildschirm­foto 2022-11-01 um 22 34 55](https://user-images.githubusercontent.com/16468234/199346199-c840eb36-99bc-4b86-849e-7b8de1176d19.png)

**Comment by Henry-Sir** [comment]
> @Henry-Sir @andre68723 @dcboy87 I think I implemented all your changes. Please try it with the latest build in the [enhance-homeassistant-discovery](https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Aenhance-homeassistant-discovery) branch.
> 
> I did not test it very intensively or played with all config options. So if you could do it, that would be of great help!
> 
> Can somebody test that the water dashboard works in the beta release of HA?
> 
> ‼️ Note: The `Value` now uses the right string for the `Device class`. Sadly for `water` this requires HA 2022.11-b3 to work 😒 . With HA 2022.6.5, the `Value` config topic simply gets ignored! As a workaround, use `Other`!
> 
> ![grafik](https://user-images.githubusercontent.com/1783586/198902544-be46c228-f850-4d91-954a-31c1f31e1d0c.png)

Looks good 😃 
The decimal digits of "Interval" could perhaps be reduced.

I currently have it set to "Other". I guess the HA 2022.11 release will come in the next 1-2 days and then I would test it again with "Water".

![grafik](https://user-images.githubusercontent.com/75314095/199439359-5cd44bda-a792-4abb-abc9-f4df518adedd.png)

**Comment by caco3** [comment]
> The decimal digits of "Interval" could perhaps be reduced.

Fixed

> I currently have it set to "Other".

I have to do the same, and i already added a note to the config.

**Comment by andre68723** [comment]
> > PS: do you plan to keep the json on the Entity sensor page? Eventually better fits into diagnostics
> 
> Yes, I was thinking about this as well. But some users prefer to only use one topic (this one) and parse it in HA to get all info. Then for those its not a diagnostic value...

Well, just noticed the Device Log Book has a lot of entries due to both - timestamp and the json. Also visible on the screenshot from @Henry-Sir 

Tasmota (plug) informs only of events like restart, wifi-changed, on/off for plugs

**Comment by caco3** [comment]
The Discovery Topics and the static topics (`IP`, `MAC`, `Hostname`, ...) only get sent on startup.
New: To trigger a resending of them, you can call the following URL: `http://<IP>/mqtt_send`

**Comment by Henry-Sir** [comment]
Hi, even if already closed I would like to make one more comment.

HA 2022.11 is now available and everything looks good. Sensor for the statistics detected and everything is running.


> > An additional alarm sensor could be added to the "Error" sensor. I have set up a "binary sensor" for this, see below.
> 
> Done (called `Problem`)

Just saw that the sensor is a type "sensor". Better would be the type "binary_sensor".
For "binary_sensor" the topic must be changed to "homeassistant/binary_sensor/...".

**Comment by caco3** [comment]
> HA 2022.11 is now available and everything looks good. Sensor for the statistics detected and everything is running.

:partying_face: 

> Just saw that the sensor is a type "sensor". Better would be the type "binary_sensor".

Thanks, I will change that.

**Comment by Henry-Sir** [comment]
I have tested the change ( Branch: 'enhance-homeassistant-discovery', Tag: '', Revision: 6a561fa 
https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3396854563).

Problem Sensor looks good.

But the interval sensor is no longer correct. Configured are 4 minutes, transmitted are 10 minutes.
The values of "JSON", "Value", etc, are also transmitted every 4 minutes.
The previous build I tested still worked. (https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3373442545)

![image](https://user-images.githubusercontent.com/75314095/200079640-ae123d8b-0b99-4602-8c7c-81cd860efcc1.png)
![image](https://user-images.githubusercontent.com/75314095/200079721-83f7af27-7e9c-4085-a21a-838ccbc70fff.png)
![image](https://user-images.githubusercontent.com/75314095/200080092-90879730-5f0c-43ab-8f8f-5d99aca01b6b.png)

**Comment by caco3** [comment]
Due to conflicts I had to create a new branch, see https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Aenhance-homeassistant-discovery-5
It will get merged to rolling in the next days.

**Comment by caco3** [comment]
> But the interval sensor is no longer correct. Configured are 4 minutes, transmitted are 10 minutes.

Yes, that was still work in progress, but now it should be correct.
