### ISSUE TITLE
It does not compile the program.

### ISSUE THREAD

**Issue by markbr04** [jomjol/AI-on-the-edge-device#2494]
### The Problem

I want to compile the program, but I don't succeed. I follow the instructions to clone the repository, I use Visual studio code version 1.79.2, I install the platform extension v3.2.0, but in the end it throws me a message that I expose in the photograph below.
Please help to solve this problem. Thank you.

### Version

Use version 15.2.4

### Logfile

```shell
esptool.py v4.5.1
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Generating project linker script .pio/build/esp32cam/sections.ld
Traceback (most recent call last):
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 152, in _get_infos_from_file
    results = parser.parseString(info.content, parseAll=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/penv/.espidf-5.0.2/lib64/python3.11/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/penv/.espidf-5.0.2/lib64/python3.11/site-packages/pyparsing/core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'default'  (at char 1), (line:2, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 183, in <module>
    main()
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 159, in main
    mapping_rules = generation_model.generate(sections_infos)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 514, in generate
    root_node.insert(entity, sections, target, flags, entities)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/generation.py", line 296, in child_placement
    found_sections = sections_db.get_sections(self.parent.name, self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 197, in get_sections
    obj = self._match_obj(archive, obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 183, in _match_obj
    objs = self.get_objects(archive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 176, in get_objects
    self._process_archive(archive)
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 164, in _process_archive
    parsed = self._get_infos_from_file(stored)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markbr88/.platformio/packages/framework-espidf/tools/ldgen/ldgen/entity.py", line 154, in _get_infos_from_file
    raise ParseException('Unable to parse section info file ' + info.filename + '. ' + p.msg)
pyparsing.exceptions.ParseException: Unable to parse section info file /home/markbr88/AI-on-the-edge-device/code/.pio/build/esp32cam/esp-idf/esp_event/libesp_event.a. Expected end of text  (at char 0), (line:1, col:1)
*** [.pio/build/esp32cam/sections.ld] Error 1
================================================= [FAILED] Took 75.83 seconds =================================================

Environment    Status    Duration
-------------  --------  ------------
esp32cam       FAILED    00:01:15.826
============================================ 1 failed, 0 succeeded in 00:01:15.826 ============================================
[markbr88@legion-dev code]$
```

### Screenshots

![imagen](https://github.com/jomjol/AI-on-the-edge-device/assets/87866972/e3e95de0-8e5e-40a5-85a5-3ed99868e43a)

**Comment by camow7** [comment]
Can confirm I'm currently getting the same results:

```
Traceback (most recent call last):
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 152, in _get_infos_from_file
    results = parser.parseString(info.content, parseAll=True)
  File "C:\Users\catch\.platformio\penv\.espidf-5.0.2\lib\site-packages\pyparsing\util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "C:\Users\catch\.platformio\penv\.espidf-5.0.2\lib\site-packages\pyparsing\core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'default'  (at char 2), (line:2, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen.py", line 183, in <module>
    main()
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen.py", line 159, in main
    mapping_rules = generation_model.generate(sections_infos)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 514, in generate
    root_node.insert(entity, sections, target, flags, entities)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\generation.py", line 296, in child_placement
    found_sections = sections_db.get_sections(self.parent.name, self.name)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 197, in get_sections
    obj = self._match_obj(archive, obj)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 183, in _match_obj
    objs = self.get_objects(archive)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 176, in get_objects
    self._process_archive(archive)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 164, in _process_archive
    parsed = self._get_infos_from_file(stored)
  File "C:\Users\catch\.platformio\packages\framework-espidf\tools\ldgen\ldgen\entity.py", line 154, in _get_infos_from_file
    raise ParseException('Unable to parse section info file ' + info.filename + '. ' + p.msg)
pyparsing.exceptions.ParseException: Unable to parse section info file C:/Users/catch/Documents/GitHub/AI-on-the-edge-device/code/.pio/build/esp32cam/esp-idf/esp_event/libesp_event.a. Expected end of text  (at char 0), (line:1, col:1)
*** [.pio\build\esp32cam\sections.ld] Error 1
==================================================================================== [FAILED] Took 262.71 seconds ====================================================================================

Environment    Status    Duration
-------------  --------  ------------
esp32cam       FAILED    00:04:22.709
================================================================================ 1 failed, 0 succeeded in 00:04:22.709 ================================================================================

PS C:\Users\catch\Documents\GitHub\AI-on-the-edge-device\code> 
```

**Comment by markbr04** [comment]
I recently migrated the operating system, I changed from ubuntu 22.04 to fedora 37. Because previously I had no problems compiling the program. Thanks for your comment.

**Comment by haverland** [comment]
Reopened, because build action of GitHub has the same issue:
https://github.com/jomjol/AI-on-the-edge-device/actions/runs/5381548148/jobs/9765761115

**Comment by caco3** [comment]
That is really odd.

I just now re-triggered building of rolling (https://github.com/jomjol/AI-on-the-edge-device/actions/runs/5247071049).
That was working ok before but now failed without a obvious change:
![grafik](https://github.com/jomjol/AI-on-the-edge-device/assets/1783586/f19a8e41-0aa2-4e92-864c-d70f2e6a5efa)

Maybe something on Github changed or something on the used toolchain (PlatformIO) changed...

**Comment by caco3** [comment]
N.B. I now updated PlatformIO to the latest version, and that builds fine: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/5416901265

**Comment by caco3** [comment]
The new PlatformIO seems to fix this issue, I merged it to rolling.

Please update and try again.
If you are working on a branch, you have to rebase it t rolling!

I will close this issue, feel free to reopen if the issue still exists.
