### ISSUE TITLE
OSError: [Errno 71] Protocol error  [upload] Error 1

### ISSUE THREAD

**Issue by RangeOfGlitching** [jomjol/AI-on-the-edge-device#850]
System: Ubuntu 22.04
pltformio: PlatformIO Core, version 6.0.2

I follow the wiki to build and upload the project.
when I execute this `pio run --target upload`
I got the log below

Processing esp32cam (platform: espressif32; board: esp32cam; framework: espidf)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html
PLATFORM: Espressif 32 (5.0.0) > AI Thinker ESP32-CAM
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.40401.0 (4.4.1) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - tool-mkfatfs @ 2.0.1 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 2.230.0 (2.30) 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 1.22851.191205 (2.28.51) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
Library Manager: Installing jomjol_configfile
Warning! Could not find the package with 'jomjol_configfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_helper
Warning! Could not find the package with 'jomjol_helper' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_wlan
Warning! Could not find the package with 'jomjol_wlan' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_image_proc
Warning! Could not find the package with 'jomjol_image_proc' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlcamera
Warning! Could not find the package with 'jomjol_controlcamera' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_flowcontroll
Warning! Could not find the package with 'jomjol_flowcontroll' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_tfliteclass
Warning! Could not find the package with 'jomjol_tfliteclass' requirements for your system 'linux_x86_64'
Library Manager: Installing tflite-lib
Warning! Could not find the package with 'tflite-lib' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_fileserver_ota
Warning! Could not find the package with 'jomjol_fileserver_ota' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_time_sntp
Warning! Could not find the package with 'jomjol_time_sntp' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_logfile
Warning! Could not find the package with 'jomjol_logfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_mqtt
Warning! Could not find the package with 'jomjol_mqtt' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlGPIO
Warning! Could not find the package with 'jomjol_controlGPIO' requirements for your system 'linux_x86_64'
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing jomjol_configfile
Warning! Could not find the package with 'jomjol_configfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_helper
Warning! Could not find the package with 'jomjol_helper' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_wlan
Warning! Could not find the package with 'jomjol_wlan' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_image_proc
Warning! Could not find the package with 'jomjol_image_proc' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlcamera
Warning! Could not find the package with 'jomjol_controlcamera' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_flowcontroll
Warning! Could not find the package with 'jomjol_flowcontroll' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_tfliteclass
Warning! Could not find the package with 'jomjol_tfliteclass' requirements for your system 'linux_x86_64'
Library Manager: Installing tflite-lib
Warning! Could not find the package with 'tflite-lib' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_fileserver_ota
Warning! Could not find the package with 'jomjol_fileserver_ota' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_time_sntp
Warning! Could not find the package with 'jomjol_time_sntp' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_logfile
Warning! Could not find the package with 'jomjol_logfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_mqtt
Warning! Could not find the package with 'jomjol_mqtt' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlGPIO
Warning! Could not find the package with 'jomjol_controlGPIO' requirements for your system 'linux_x86_64'
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Retrieving maximum program size .pio/build/esp32cam/firmware.elf
Checking size .pio/build/esp32cam/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  19.7% (used 64692 bytes from 327680 bytes)
Flash: [========= ]  87.7% (used 1705709 bytes from 1945600 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Using manually specified: /dev/ttyUSB0
Uploading .pio/build/esp32cam/firmware.bin
esptool.py v3.3
Serial port /dev/ttyUSB0
Connecting...
Traceback (most recent call last):
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 5387, in <module>
    _main()
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 5380, in _main
    main()
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 4687, in main
    esp = esp or get_default_connected_device(ser_list, port=args.port, connect_attempts=args.connect_attempts,
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 115, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 664, in connect
    last_error = self._connect_attempt(mode=mode, usb_jtag_serial=usb_jtag_serial, extra_delay=extra_delay)
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 614, in _connect_attempt
    self.bootloader_reset(usb_jtag_serial, extra_delay)
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 595, in bootloader_reset
    self._setDTR(True)   # IO0=LOW
  File "/home/dodo/.platformio/packages/tool-esptoolpy/esptool.py", line 532, in _setDTR
    self._port.setDTR(state)
  File "/home/dodo/.platformio/penv/lib/python3.10/site-packages/serial/serialutil.py", line 603, in setDTR
    self.dtr = value
  File "/home/dodo/.platformio/penv/lib/python3.10/site-packages/serial/serialutil.py", line 473, in dtr
    self._update_dtr_state()
  File "/home/dodo/.platformio/penv/lib/python3.10/site-packages/serial/serialposix.py", line 713, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 71] Protocol error
*** [upload] Error 1

**Comment by RangeOfGlitching** [comment]
I don't know how, but after reboot system I can upload it without any error.
dodo@dodo:~/Desktop/esp32/AI-on-the-edge-device/code$ pio run --target upload
Processing esp32cam (platform: espressif32; board: esp32cam; framework: espidf)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html
PLATFORM: Espressif 32 (5.0.0) > AI Thinker ESP32-CAM
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.40401.0 (4.4.1) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - tool-mkfatfs @ 2.0.1 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 2.230.0 (2.30) 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 1.22851.191205 (2.28.51) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
Library Manager: Installing jomjol_configfile
Warning! Could not find the package with 'jomjol_configfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_helper
Warning! Could not find the package with 'jomjol_helper' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_wlan
Warning! Could not find the package with 'jomjol_wlan' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_image_proc
Warning! Could not find the package with 'jomjol_image_proc' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlcamera
Warning! Could not find the package with 'jomjol_controlcamera' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_flowcontroll
Warning! Could not find the package with 'jomjol_flowcontroll' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_tfliteclass
Warning! Could not find the package with 'jomjol_tfliteclass' requirements for your system 'linux_x86_64'
Library Manager: Installing tflite-lib
Warning! Could not find the package with 'tflite-lib' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_fileserver_ota
Warning! Could not find the package with 'jomjol_fileserver_ota' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_time_sntp
Warning! Could not find the package with 'jomjol_time_sntp' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_logfile
Warning! Could not find the package with 'jomjol_logfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_mqtt
Warning! Could not find the package with 'jomjol_mqtt' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlGPIO
Warning! Could not find the package with 'jomjol_controlGPIO' requirements for your system 'linux_x86_64'
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing jomjol_configfile
Warning! Could not find the package with 'jomjol_configfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_helper
Warning! Could not find the package with 'jomjol_helper' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_wlan
Warning! Could not find the package with 'jomjol_wlan' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_image_proc
Warning! Could not find the package with 'jomjol_image_proc' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlcamera
Warning! Could not find the package with 'jomjol_controlcamera' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_flowcontroll
Warning! Could not find the package with 'jomjol_flowcontroll' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_tfliteclass
Warning! Could not find the package with 'jomjol_tfliteclass' requirements for your system 'linux_x86_64'
Library Manager: Installing tflite-lib
Warning! Could not find the package with 'tflite-lib' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_fileserver_ota
Warning! Could not find the package with 'jomjol_fileserver_ota' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_time_sntp
Warning! Could not find the package with 'jomjol_time_sntp' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_logfile
Warning! Could not find the package with 'jomjol_logfile' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_mqtt
Warning! Could not find the package with 'jomjol_mqtt' requirements for your system 'linux_x86_64'
Library Manager: Installing jomjol_controlGPIO
Warning! Could not find the package with 'jomjol_controlGPIO' requirements for your system 'linux_x86_64'
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Retrieving maximum program size .pio/build/esp32cam/firmware.elf
Checking size .pio/build/esp32cam/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  19.7% (used 64692 bytes from 327680 bytes)
Flash: [========= ]  87.7% (used 1705709 bytes from 1945600 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Using manually specified: /dev/ttyUSB0
Uploading .pio/build/esp32cam/firmware.bin
esptool.py v3.3
Serial port /dev/ttyUSB0
Connecting.....
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: c4:dd:57:ea:c4:c4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00007fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000d000 to 0x0000efff...
Flash will be erased from 0x00010000 to 0x001b1fff...
Compressed 25792 bytes to 16027...
Writing at 0x00001000... (100 %)
Wrote 25792 bytes (16027 compressed) at 0x00001000 in 0.7 seconds (effective 306.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 556.6 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 31...
Writing at 0x0000d000... (100 %)
Wrote 8192 bytes (31 compressed) at 0x0000d000 in 0.1 seconds (effective 787.0 kbit/s)...
Hash of data verified.
Compressed 1711488 bytes to 1042593...
Writing at 0x00010000... (1 %)
Writing at 0x0001b2ee... (3 %)
Writing at 0x00026a37... (4 %)
Writing at 0x00030861... (6 %)
Writing at 0x0003b43a... (7 %)
Writing at 0x00048b1d... (9 %)
Writing at 0x0005b74e... (10 %)
Writing at 0x00060f7c... (12 %)
Writing at 0x00066994... (14 %)
Writing at 0x0006bf70... (15 %)
Writing at 0x00071665... (17 %)
Writing at 0x00076d7c... (18 %)
Writing at 0x0007be87... (20 %)
Writing at 0x00081763... (21 %)
Writing at 0x00086bf8... (23 %)
Writing at 0x0008c227... (25 %)
Writing at 0x00091be2... (26 %)
Writing at 0x00096ded... (28 %)
Writing at 0x0009c2db... (29 %)
Writing at 0x000a1773... (31 %)
Writing at 0x000a697f... (32 %)
Writing at 0x000abe16... (34 %)
Writing at 0x000b18ca... (35 %)
Writing at 0x000b6a87... (37 %)
Writing at 0x000bc033... (39 %)
Writing at 0x000c202f... (40 %)
Writing at 0x000c765c... (42 %)
Writing at 0x000cc831... (43 %)
Writing at 0x000d1aac... (45 %)
Writing at 0x000d6cde... (46 %)
Writing at 0x000dc0c7... (48 %)
Writing at 0x000e145e... (50 %)
Writing at 0x000e6a1c... (51 %)
Writing at 0x000ec2f6... (53 %)
Writing at 0x000f202f... (54 %)
Writing at 0x000f7acd... (56 %)
Writing at 0x000fe734... (57 %)
Writing at 0x00107f5f... (59 %)
Writing at 0x0010ec9d... (60 %)
Writing at 0x00118017... (62 %)
Writing at 0x0011ddbe... (64 %)
Writing at 0x00124237... (65 %)
Writing at 0x0012a4e0... (67 %)
Writing at 0x0012f717... (68 %)
Writing at 0x0013965e... (70 %)
Writing at 0x00140abb... (71 %)
Writing at 0x00145e30... (73 %)
Writing at 0x0014bcf7... (75 %)
Writing at 0x00151b9e... (76 %)
Writing at 0x00157409... (78 %)
Writing at 0x0015cc1c... (79 %)
Writing at 0x001622b0... (81 %)
Writing at 0x001673d0... (82 %)
Writing at 0x0016d006... (84 %)
Writing at 0x00172830... (85 %)
Writing at 0x001783b6... (87 %)
Writing at 0x0017f174... (89 %)
Writing at 0x00187037... (90 %)
Writing at 0x00190bd3... (92 %)
Writing at 0x001989c5... (93 %)
Writing at 0x0019e3da... (95 %)
Writing at 0x001a398b... (96 %)
Writing at 0x001a90c5... (98 %)
Writing at 0x001ae5a9... (100 %)
Wrote 1711488 bytes (1042593 compressed) at 0x00010000 in 25.6 seconds (effective 534.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
================================================================== [SUCCESS] Took 56.89 seconds ==================================================================
